apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: test-python
  name: test-python
spec:
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app.kubernetes.io/name: test-python
  type: ClusterIP
